### ISSUE TITLE
Create the substance inside Register.jsx component

### ISSUE THREAD

**Issue by iris-riddell** [pohutukawa-2019/ChatWell#12]
REWORDED TICKET:
This should be a random username file for a component to pull a random username from which the app chooses randomly.

**Comment by m-hod** [comment]
this is generating random usernames, but there is no component to actually display those usernames. could you please turn the current file into utilities.js, then make a Username.jsx file that pulls this in. Please refer to the initial ticket details for what the Username.jsx component should contain.
